export const data = JSON.parse("{\"key\":\"v-12ac8c42\",\"path\":\"/design-pattern/behavioral/template-method.html\",\"title\":\"设计模式-模版方法\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"设计模式-模版方法\",\"date\":\"2022-12-11T00:00:00.000Z\",\"tag\":[\"Go\",\"行为型模式\"],\"category\":[\"设计模式\"],\"description\":\"template-method\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://Hexiaopi.github.io/design-pattern/behavioral/template-method.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Hexiaopi\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"设计模式-模版方法\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"template-method\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Hexiaopi\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Go\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"行为型模式\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-12-11T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"设计模式-模版方法\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2022-12-11T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Hexiaopi\\\",\\\"url\\\":\\\"https://github.com/Hexiaopi\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"场景问题\",\"slug\":\"场景问题\",\"link\":\"#场景问题\",\"children\":[]},{\"level\":2,\"title\":\"什么是模版方法模式\",\"slug\":\"什么是模版方法模式\",\"link\":\"#什么是模版方法模式\",\"children\":[{\"level\":3,\"title\":\"包含哪些角色\",\"slug\":\"包含哪些角色\",\"link\":\"#包含哪些角色\",\"children\":[]},{\"level\":3,\"title\":\"代码示例\",\"slug\":\"代码示例\",\"link\":\"#代码示例\",\"children\":[]}]},{\"level\":2,\"title\":\"总结\",\"slug\":\"总结\",\"link\":\"#总结\",\"children\":[{\"level\":3,\"title\":\"优点\",\"slug\":\"优点\",\"link\":\"#优点\",\"children\":[]},{\"level\":3,\"title\":\"缺点\",\"slug\":\"缺点\",\"link\":\"#缺点\",\"children\":[]}]}],\"readingTime\":{\"minutes\":2.24,\"words\":671},\"filePathRelative\":\"design-pattern/behavioral/template-method.md\",\"localizedDate\":\"2022年12月11日\",\"excerpt\":\"<figure><img src=\\\"https://refactoringguru.cn/images/patterns/content/template-method/template-method-2x.png\\\" alt=\\\"template-method\\\" tabindex=\\\"0\\\" loading=\\\"lazy\\\"><figcaption>template-method</figcaption></figure>\\n\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
