export const data = JSON.parse("{\"key\":\"v-7a3fa2b0\",\"path\":\"/design-pattern/behavioral/visitor.html\",\"title\":\"设计模式-访问者\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"设计模式-访问者\",\"date\":\"2023-05-05T00:00:00.000Z\",\"tag\":[\"Go\",\"行为型模式\"],\"category\":[\"设计模式\"],\"description\":\"visitor\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://Hexiaopi.github.io/design-pattern/behavioral/visitor.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Hexiaopi\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"设计模式-访问者\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"visitor\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Hexiaopi\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Go\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"行为型模式\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-05-05T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"设计模式-访问者\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2023-05-05T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Hexiaopi\\\",\\\"url\\\":\\\"https://github.com/Hexiaopi\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"什么是访问者模式\",\"slug\":\"什么是访问者模式\",\"link\":\"#什么是访问者模式\",\"children\":[{\"level\":3,\"title\":\"包含哪些角色\",\"slug\":\"包含哪些角色\",\"link\":\"#包含哪些角色\",\"children\":[]},{\"level\":3,\"title\":\"代码示例\",\"slug\":\"代码示例\",\"link\":\"#代码示例\",\"children\":[]}]},{\"level\":2,\"title\":\"应用场景\",\"slug\":\"应用场景\",\"link\":\"#应用场景\",\"children\":[{\"level\":3,\"title\":\"在不修改已有代码的情况下，向已有类层次结构增加新的行为\",\"slug\":\"在不修改已有代码的情况下-向已有类层次结构增加新的行为\",\"link\":\"#在不修改已有代码的情况下-向已有类层次结构增加新的行为\",\"children\":[]}]},{\"level\":2,\"title\":\"总结\",\"slug\":\"总结\",\"link\":\"#总结\",\"children\":[{\"level\":3,\"title\":\"优点\",\"slug\":\"优点\",\"link\":\"#优点\",\"children\":[]},{\"level\":3,\"title\":\"缺点\",\"slug\":\"缺点\",\"link\":\"#缺点\",\"children\":[]}]}],\"readingTime\":{\"minutes\":3.01,\"words\":902},\"filePathRelative\":\"design-pattern/behavioral/visitor.md\",\"localizedDate\":\"2023年5月5日\",\"excerpt\":\"<figure><img src=\\\"https://refactoringguru.cn/images/patterns/content/visitor/visitor-2x.png\\\" alt=\\\"visitor\\\" tabindex=\\\"0\\\" loading=\\\"lazy\\\"><figcaption>visitor</figcaption></figure>\\n\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
