export const data = JSON.parse("{\"key\":\"v-76a20065\",\"path\":\"/project-standard/code/commit.html\",\"title\":\"提交规范\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"提交规范\",\"date\":\"2020-02-02T00:00:00.000Z\",\"tag\":[\"规范\"],\"category\":[\"项目规范\"],\"description\":\"Commit Message Git每次提交代码，都需要写Commit message，好的规范例如：Angular规范，可以帮助我们： 根据摘要信息就可以知道每次变更哪些内容 可以过滤某些commit，例如只关注新增加的功能 根据commit生成Change log\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://Hexiaopi.github.io/project-standard/code/commit.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Hexiaopi\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"提交规范\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Commit Message Git每次提交代码，都需要写Commit message，好的规范例如：Angular规范，可以帮助我们： 根据摘要信息就可以知道每次变更哪些内容 可以过滤某些commit，例如只关注新增加的功能 根据commit生成Change log\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Hexiaopi\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"规范\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2020-02-02T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"提交规范\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2020-02-02T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Hexiaopi\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Commit Message\",\"slug\":\"commit-message\",\"link\":\"#commit-message\",\"children\":[{\"level\":3,\"title\":\"Header（必须项）\",\"slug\":\"header-必须项\",\"link\":\"#header-必须项\",\"children\":[]},{\"level\":3,\"title\":\"Body（可选项）\",\"slug\":\"body-可选项\",\"link\":\"#body-可选项\",\"children\":[]},{\"level\":3,\"title\":\"Footer（可选项）\",\"slug\":\"footer-可选项\",\"link\":\"#footer-可选项\",\"children\":[]}]},{\"level\":2,\"title\":\"Change Log\",\"slug\":\"change-log\",\"link\":\"#change-log\",\"children\":[]},{\"level\":2,\"title\":\"SemVer\",\"slug\":\"semver\",\"link\":\"#semver\",\"children\":[]}],\"readingTime\":{\"minutes\":2.3,\"words\":689},\"filePathRelative\":\"project-standard/code/commit.md\",\"localizedDate\":\"2020年2月2日\",\"excerpt\":\"<h2> Commit Message</h2>\\n<p>Git每次提交代码，都需要写<code>Commit message</code>，好的规范例如：<a href=\\\"https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#-commit-message-guidelines\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">Angular规范</a>，可以帮助我们：</p>\\n<ul>\\n<li>根据摘要信息就可以知道每次变更哪些内容</li>\\n<li>可以过滤某些commit，例如只关注新增加的功能</li>\\n<li>根据commit生成<code>Change log</code></li>\\n</ul>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
