export const data = JSON.parse("{\"key\":\"v-41a2d2ec\",\"path\":\"/design-pattern/creational/abstract-factory.html\",\"title\":\"设计模式-抽象工厂\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"设计模式-抽象工厂\",\"date\":\"2022-10-15T00:00:00.000Z\",\"tag\":[\"Go\",\"创建型模式\"],\"category\":[\"设计模式\"],\"description\":\"abstract-factory\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://Hexiaopi.github.io/design-pattern/creational/abstract-factory.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Hexiaopi\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"设计模式-抽象工厂\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"abstract-factory\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Hexiaopi\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Go\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"创建型模式\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-10-15T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"设计模式-抽象工厂\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2022-10-15T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Hexiaopi\\\",\\\"url\\\":\\\"https://github.com/Hexiaopi\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"什么是抽象工厂模式\",\"slug\":\"什么是抽象工厂模式\",\"link\":\"#什么是抽象工厂模式\",\"children\":[{\"level\":3,\"title\":\"包含哪些角色\",\"slug\":\"包含哪些角色\",\"link\":\"#包含哪些角色\",\"children\":[]},{\"level\":3,\"title\":\"代码示例\",\"slug\":\"代码示例\",\"link\":\"#代码示例\",\"children\":[]},{\"level\":3,\"title\":\"应用场景\",\"slug\":\"应用场景\",\"link\":\"#应用场景\",\"children\":[]},{\"level\":3,\"title\":\"有哪些优缺点\",\"slug\":\"有哪些优缺点\",\"link\":\"#有哪些优缺点\",\"children\":[]}]},{\"level\":2,\"title\":\"总结\",\"slug\":\"总结\",\"link\":\"#总结\",\"children\":[{\"level\":3,\"title\":\"简单工厂、工厂方法和抽象工厂的区别\",\"slug\":\"简单工厂、工厂方法和抽象工厂的区别\",\"link\":\"#简单工厂、工厂方法和抽象工厂的区别\",\"children\":[]}]}],\"readingTime\":{\"minutes\":3.83,\"words\":1150},\"filePathRelative\":\"design-pattern/creational/abstract-factory.md\",\"localizedDate\":\"2022年10月15日\",\"excerpt\":\"<figure><img src=\\\"https://refactoringguru.cn/images/patterns/content/abstract-factory/abstract-factory-zh-2x.png\\\" alt=\\\"abstract-factory\\\" tabindex=\\\"0\\\" loading=\\\"lazy\\\"><figcaption>abstract-factory</figcaption></figure>\\n\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
