export const data = JSON.parse("{\"key\":\"v-86bb0b02\",\"path\":\"/design-pattern/creational/object-pool.html\",\"title\":\"设计模式-对象池\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"设计模式-对象池\",\"date\":\"2023-04-16T00:00:00.000Z\",\"tag\":[\"Go\",\"创建型模式\"],\"category\":[\"设计模式\"],\"description\":\"什么是对象池模式 对象池模式(Object Pool Pattern)：它通过预先创建和初始化一组对象，然后将它们存放在一个池中，以便在需要时重复使用。这样可以减少频繁创建和销毁对象的开销，提高应用程序的性能和效率。 包含哪些角色 object-pool Pool：对象池; 对象池维护活动对象列表和空闲对象列表 Object：对象; 对象被客户端使用 ...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://Hexiaopi.github.io/design-pattern/creational/object-pool.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Hexiaopi\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"设计模式-对象池\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"什么是对象池模式 对象池模式(Object Pool Pattern)：它通过预先创建和初始化一组对象，然后将它们存放在一个池中，以便在需要时重复使用。这样可以减少频繁创建和销毁对象的开销，提高应用程序的性能和效率。 包含哪些角色 object-pool Pool：对象池; 对象池维护活动对象列表和空闲对象列表 Object：对象; 对象被客户端使用 ...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Hexiaopi\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Go\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"创建型模式\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-04-16T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"设计模式-对象池\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2023-04-16T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Hexiaopi\\\",\\\"url\\\":\\\"https://github.com/Hexiaopi\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"什么是对象池模式\",\"slug\":\"什么是对象池模式\",\"link\":\"#什么是对象池模式\",\"children\":[{\"level\":3,\"title\":\"包含哪些角色\",\"slug\":\"包含哪些角色\",\"link\":\"#包含哪些角色\",\"children\":[]},{\"level\":3,\"title\":\"代码示例\",\"slug\":\"代码示例\",\"link\":\"#代码示例\",\"children\":[]},{\"level\":3,\"title\":\"使用场景\",\"slug\":\"使用场景\",\"link\":\"#使用场景\",\"children\":[]},{\"level\":3,\"title\":\"有哪些优缺点\",\"slug\":\"有哪些优缺点\",\"link\":\"#有哪些优缺点\",\"children\":[]}]},{\"level\":2,\"title\":\"总结\",\"slug\":\"总结\",\"link\":\"#总结\",\"children\":[]}],\"readingTime\":{\"minutes\":3.68,\"words\":1103},\"filePathRelative\":\"design-pattern/creational/object-pool.md\",\"localizedDate\":\"2023年4月16日\",\"excerpt\":\"\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
