export const data = JSON.parse("{\"key\":\"v-98eaee04\",\"path\":\"/design-pattern/creational/singleton.html\",\"title\":\"设计模式-单例\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"设计模式-单例\",\"date\":\"2022-10-17T00:00:00.000Z\",\"tag\":[\"Go\",\"创建型模式\"],\"category\":[\"设计模式\"],\"description\":\"singleton\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://Hexiaopi.github.io/design-pattern/creational/singleton.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Hexiaopi\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"设计模式-单例\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"singleton\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Hexiaopi\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Go\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"创建型模式\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-10-17T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"设计模式-单例\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2022-10-17T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Hexiaopi\\\",\\\"url\\\":\\\"https://github.com/Hexiaopi\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"什么是单例模式\",\"slug\":\"什么是单例模式\",\"link\":\"#什么是单例模式\",\"children\":[{\"level\":3,\"title\":\"包含哪些角色\",\"slug\":\"包含哪些角色\",\"link\":\"#包含哪些角色\",\"children\":[]},{\"level\":3,\"title\":\"有哪些类别\",\"slug\":\"有哪些类别\",\"link\":\"#有哪些类别\",\"children\":[]},{\"level\":3,\"title\":\"有哪些特点\",\"slug\":\"有哪些特点\",\"link\":\"#有哪些特点\",\"children\":[]},{\"level\":3,\"title\":\"有哪些应用场景\",\"slug\":\"有哪些应用场景\",\"link\":\"#有哪些应用场景\",\"children\":[]},{\"level\":3,\"title\":\"有哪些优缺点\",\"slug\":\"有哪些优缺点\",\"link\":\"#有哪些优缺点\",\"children\":[]}]},{\"level\":2,\"title\":\"代码示例\",\"slug\":\"代码示例\",\"link\":\"#代码示例\",\"children\":[{\"level\":3,\"title\":\"Sync.Mutex 方式\",\"slug\":\"sync-mutex-方式\",\"link\":\"#sync-mutex-方式\",\"children\":[]},{\"level\":3,\"title\":\"init() 函数方式\",\"slug\":\"init-函数方式\",\"link\":\"#init-函数方式\",\"children\":[]},{\"level\":3,\"title\":\"sync.Once 方式\",\"slug\":\"sync-once-方式\",\"link\":\"#sync-once-方式\",\"children\":[]}]}],\"readingTime\":{\"minutes\":3.33,\"words\":1000},\"filePathRelative\":\"design-pattern/creational/singleton.md\",\"localizedDate\":\"2022年10月17日\",\"excerpt\":\"<figure><img src=\\\"https://refactoringguru.cn/images/patterns/content/singleton/singleton-2x.png\\\" alt=\\\"singleton\\\" tabindex=\\\"0\\\" loading=\\\"lazy\\\"><figcaption>singleton</figcaption></figure>\\n\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
