export const data = JSON.parse("{\"key\":\"v-4333bb0a\",\"path\":\"/go-language/base/variable.html\",\"title\":\"变量\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"变量\",\"date\":\"2022-01-23T00:00:00.000Z\",\"tag\":[\"Go\",\"基础\"],\"category\":[\"Go语言\"],\"description\":\"变量 程序运行过程中，数据常常分配在内存中，我们在编码阶段用一个易于阅读的名字来定义这块内存，这块内存上存储的数据其值可以经常改变，我们就称为变量(variable) 变量的类型决定了变量在内存的长度和存储格式 声明 一个变量 var &lt;variable_name&gt; [variable_type]\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://Hexiaopi.github.io/go-language/base/variable.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Hexiaopi\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"变量\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"变量 程序运行过程中，数据常常分配在内存中，我们在编码阶段用一个易于阅读的名字来定义这块内存，这块内存上存储的数据其值可以经常改变，我们就称为变量(variable) 变量的类型决定了变量在内存的长度和存储格式 声明 一个变量 var &lt;variable_name&gt; [variable_type]\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Hexiaopi\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Go\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"基础\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-01-23T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"变量\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2022-01-23T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Hexiaopi\\\",\\\"url\\\":\\\"https://github.com/Hexiaopi\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"变量\",\"slug\":\"变量\",\"link\":\"#变量\",\"children\":[{\"level\":3,\"title\":\"声明\",\"slug\":\"声明\",\"link\":\"#声明\",\"children\":[]},{\"level\":3,\"title\":\"零值\",\"slug\":\"零值\",\"link\":\"#零值\",\"children\":[]},{\"level\":3,\"title\":\"作用域\",\"slug\":\"作用域\",\"link\":\"#作用域\",\"children\":[]},{\"level\":3,\"title\":\"声明原则\",\"slug\":\"声明原则\",\"link\":\"#声明原则\",\"children\":[]}]}],\"readingTime\":{\"minutes\":3.37,\"words\":1011},\"filePathRelative\":\"go-language/base/variable.md\",\"localizedDate\":\"2022年1月23日\",\"excerpt\":\"<h2> 变量</h2>\\n<blockquote>\\n<p>程序运行过程中，数据常常分配在内存中，我们在编码阶段用一个易于阅读的名字来定义这块内存，这块内存上存储的数据其值可以经常改变，我们就称为变量(variable)</p>\\n<p>变量的类型决定了变量在内存的长度和存储格式</p>\\n</blockquote>\\n<h3> 声明</h3>\\n<h4> 一个变量</h4>\\n<div class=\\\"language-go line-numbers-mode\\\" data-ext=\\\"go\\\"><pre class=\\\"language-go\\\"><code><span class=\\\"token keyword\\\">var</span> <span class=\\\"token operator\\\">&lt;</span>variable_name<span class=\\\"token operator\\\">&gt;</span> <span class=\\\"token punctuation\\\">[</span>variable_type<span class=\\\"token punctuation\\\">]</span>\\n</code></pre><div class=\\\"line-numbers\\\" aria-hidden=\\\"true\\\"><div class=\\\"line-number\\\"></div></div></div>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
