export const data = JSON.parse("{\"key\":\"v-d2187c5c\",\"path\":\"/project-standard/branch.html\",\"title\":\"分支规范\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"分支规范\",\"date\":\"2020-02-11T00:00:00.000Z\",\"tag\":[\"规范\",\"分支\"],\"category\":[\"项目规范\"],\"description\":\"git-model 提示 一个好的代码分支应该是怎样的❓\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://Hexiaopi.github.io/project-standard/branch.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Hexiaopi\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"分支规范\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"git-model 提示 一个好的代码分支应该是怎样的❓\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Hexiaopi\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"规范\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"分支\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2020-02-11T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"分支规范\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2020-02-11T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Hexiaopi\\\",\\\"url\\\":\\\"https://github.com/Hexiaopi\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"分支模型\",\"slug\":\"分支模型\",\"link\":\"#分支模型\",\"children\":[]},{\"level\":2,\"title\":\"master分支\",\"slug\":\"master分支\",\"link\":\"#master分支\",\"children\":[]},{\"level\":2,\"title\":\"develop分支\",\"slug\":\"develop分支\",\"link\":\"#develop分支\",\"children\":[]},{\"level\":2,\"title\":\"feature分支\",\"slug\":\"feature分支\",\"link\":\"#feature分支\",\"children\":[]},{\"level\":2,\"title\":\"release分支\",\"slug\":\"release分支\",\"link\":\"#release分支\",\"children\":[]},{\"level\":2,\"title\":\"hotfix分支\",\"slug\":\"hotfix分支\",\"link\":\"#hotfix分支\",\"children\":[]}],\"readingTime\":{\"minutes\":1.5,\"words\":451},\"filePathRelative\":\"project-standard/branch.md\",\"localizedDate\":\"2020年2月11日\",\"excerpt\":\"<figure><img src=\\\"https://www.ruanyifeng.com/blogimg/asset/2015/bg2015122301.png\\\" alt=\\\"git-model\\\" tabindex=\\\"0\\\" loading=\\\"lazy\\\"><figcaption>git-model</figcaption></figure>\\n<div class=\\\"hint-container tip\\\">\\n<p class=\\\"hint-container-title\\\">提示</p>\\n<p>一个好的代码分支应该是怎样的❓</p>\\n</div>\\n\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
