export const data = JSON.parse("{\"key\":\"v-a233bfd2\",\"path\":\"/algorithm/limit.html\",\"title\":\"限流\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"限流 限流，是一种自我保护的机制，服务端通过一些限流手段控制并发访问请求，目的是为了防止系统因突发流量导致服务不可用或者崩溃。 常用的限流方法： 计数器限流 滑动窗口限流 漏桶限流 令牌桶限流 计数器限流 在一段时间间隔内，对请求进行计数，与阈值进行比较判断是否需要限流 时间结束后重置计数器 因此计数器限流也叫固定时间限流\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://Hexiaopi.github.io/algorithm/limit.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Hexiaopi\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"限流\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"限流 限流，是一种自我保护的机制，服务端通过一些限流手段控制并发访问请求，目的是为了防止系统因突发流量导致服务不可用或者崩溃。 常用的限流方法： 计数器限流 滑动窗口限流 漏桶限流 令牌桶限流 计数器限流 在一段时间间隔内，对请求进行计数，与阈值进行比较判断是否需要限流 时间结束后重置计数器 因此计数器限流也叫固定时间限流\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://Hexiaopi.github.io/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"限流\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Hexiaopi\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"限流\\\",\\\"image\\\":[\\\"https://Hexiaopi.github.io/\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Hexiaopi\\\",\\\"url\\\":\\\"https://github.com/Hexiaopi\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"计数器限流\",\"slug\":\"计数器限流\",\"link\":\"#计数器限流\",\"children\":[{\"level\":3,\"title\":\"单机版\",\"slug\":\"单机版\",\"link\":\"#单机版\",\"children\":[]},{\"level\":3,\"title\":\"分布式\",\"slug\":\"分布式\",\"link\":\"#分布式\",\"children\":[]}]},{\"level\":2,\"title\":\"滑动窗口限流\",\"slug\":\"滑动窗口限流\",\"link\":\"#滑动窗口限流\",\"children\":[{\"level\":3,\"title\":\"分布式\",\"slug\":\"分布式-1\",\"link\":\"#分布式-1\",\"children\":[]}]},{\"level\":2,\"title\":\"漏桶限流\",\"slug\":\"漏桶限流\",\"link\":\"#漏桶限流\",\"children\":[{\"level\":3,\"title\":\"单机版\",\"slug\":\"单机版-1\",\"link\":\"#单机版-1\",\"children\":[]}]},{\"level\":2,\"title\":\"令牌桶限流\",\"slug\":\"令牌桶限流\",\"link\":\"#令牌桶限流\",\"children\":[{\"level\":3,\"title\":\"分布式\",\"slug\":\"分布式-2\",\"link\":\"#分布式-2\",\"children\":[]}]}],\"readingTime\":{\"minutes\":6.89,\"words\":2067},\"filePathRelative\":\"algorithm/limit.md\",\"excerpt\":\"<h1> 限流</h1>\\n<blockquote>\\n<p>限流，是一种自我保护的机制，服务端通过一些限流手段控制并发访问请求，目的是为了防止系统因突发流量导致服务不可用或者崩溃。</p>\\n</blockquote>\\n<p>常用的限流方法：</p>\\n<ul>\\n<li>计数器限流</li>\\n<li>滑动窗口限流</li>\\n<li>漏桶限流</li>\\n<li>令牌桶限流</li>\\n</ul>\\n<h2> 计数器限流</h2>\\n<blockquote>\\n<p>在一段时间间隔内，对请求进行计数，与阈值进行比较判断是否需要限流</p>\\n<p>时间结束后重置计数器</p>\\n<p>因此计数器限流也叫固定时间限流</p>\\n</blockquote>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
